### ISSUE TITLE
Error when trying to start program

### ISSUE THREAD

**Issue by Blueberryy** [wattostudios/GameImager#1]
![image](https://github.com/wattostudios/GameImager/assets/36592509/a5b5a904-2333-4def-8ecf-a6f2828b3a76)

**Comment by wattostudios** [comment]
Please note that, as per the description of this Project, ...

> This tool is completely unsupported by wattostudios - it has been written a long time ago, it has not been maintained, and we will not provide any support for the use of it. We recommend using Game Extractor in preference to Game Imager, but this source code may still be useful to some people.

That said, rather than using the GameImager.exe file, please try running Game Imager using the GameImager.bat file, or even just double-clicking on the GameImager.jar file. You could also try running it manually using some of the instructions in the Readme file.

**Comment by Blueberryy** [comment]
> Please note that, as per the description of this Project, ...
> 
> > This tool is completely unsupported by wattostudios - it has been written a long time ago, it has not been maintained, and we will not provide any support for the use of it. We recommend using Game Extractor in preference to Game Imager, but this source code may still be useful to some people.
> 
> That said, rather than using the GameImager.exe file, please try running Game Imager using the GameImager.bat file, or even just double-clicking on the GameImager.jar file. You could also try running it manually using some of the instructions in the Readme file.

Ah thanks for the info
